curl https://www.spotgroningen.nl/programma/herman-van-veen-11/ -o details-test-case-run-2/programma/herman-van-veen-11
curl https://www.spotgroningen.nl/programma/sarah-shook-the-disarmers/ -o details-test-case-run-2/programma/sarah-shook-the-disarmers
curl https://www.spotgroningen.nl/programma/michael-patrick-kelly/ -o details-test-case-run-2/programma/michael-patrick-kelly
curl https://www.spotgroningen.nl/programma/swamp-dogg/ -o details-test-case-run-2/programma/swamp-dogg
curl https://www.spotgroningen.nl/programma/keb-mo/ -o details-test-case-run-2/programma/keb-mo
curl https://www.spotgroningen.nl/programma/noord-nederlands-toneel-75/ -o details-test-case-run-2/programma/noord-nederlands-toneel-75
curl https://www.spotgroningen.nl/programma/noord-nederlands-toneel-76/ -o details-test-case-run-2/programma/noord-nederlands-toneel-76
curl https://www.spotgroningen.nl/programma/patrimonium-harmonie/ -o details-test-case-run-2/programma/patrimonium-harmonie
curl https://www.spotgroningen.nl/programma/noord-nederlands-toneel-74/ -o details-test-case-run-2/programma/noord-nederlands-toneel-74
curl https://www.spotgroningen.nl/programma/the-analogues/ -o details-test-case-run-2/programma/the-analogues
